version: '3.8'

services:
    server:
        build:
            context: .
            dockerfile: ./Dockerfile
        privileged: true
        volumes:
            - .:/protocol
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            net1:
              ipv4_address: 172.7.0.1
    client1:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/protocol
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            net1:
              ipv4_address: 172.7.0.2
    client2:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/protocol
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            net1:
              ipv4_address: 172.7.0.3
    client3:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/protocol
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            net1:
              ipv4_address: 172.7.0.4
networks:
    net1:
        ipam:
            driver: default
            config:
                - subnet: 172.7.0.0/16
                  gateway: 172.7.1.1

